import Foundation

/// Protocol for localization providers
/// This allows easy integration with services like Phrase, Lokalise, etc.
protocol LocalizationProvider {
    func localizedString(forKey key: String, comment: String) -> String
}

/// Default localization provider using iOS Localizable.strings
struct DefaultLocalizationProvider: LocalizationProvider {
    func localizedString(forKey key: String, comment: String) -> String {
        return NSLocalizedString(key, comment: comment)
    }
}

/// Centralized localization service
/// Makes it easy to switch localization providers or add remote translation services
class LocalizationService {
    static let shared = LocalizationService()
    
    private var provider: LocalizationProvider
    
    private init(provider: LocalizationProvider = DefaultLocalizationProvider()) {
        self.provider = provider
    }
    
    /// Update the localization provider (e.g., to use Phrase or another service)
    func setProvider(_ provider: LocalizationProvider) {
        self.provider = provider
    }
    
    // MARK: - Common Strings
    
    func client() -> String {
        provider.localizedString(forKey: "Client", comment: "Client label")
    }
    
    func date() -> String {
        provider.localizedString(forKey: "Date", comment: "Date label")
    }
    
    func share() -> String {
        provider.localizedString(forKey: "Share", comment: "Share button")
    }
    
    func done() -> String {
        provider.localizedString(forKey: "Done", comment: "Done button")
    }
    
    // MARK: - Share/Export Strings
    
    func costEstimate() -> String {
        provider.localizedString(forKey: "COST ESTIMATE", comment: "Cost estimate title")
    }
    
    func materials() -> String {
        provider.localizedString(forKey: "MATERIALS", comment: "Materials section header")
    }
    
    func materialsTotal() -> String {
        provider.localizedString(forKey: "Materials Total:", comment: "Materials total label")
    }
    
    func labor() -> String {
        provider.localizedString(forKey: "LABOR", comment: "Labor section header")
    }
    
    func laborTotal() -> String {
        provider.localizedString(forKey: "Labor Total:", comment: "Labor total label")
    }
    
    func totalCost() -> String {
        provider.localizedString(forKey: "TOTAL COST", comment: "Total cost header")
    }
    
    func total() -> String {
        provider.localizedString(forKey: "TOTAL:", comment: "Total label")
    }
    
    func generatedByCostivo() -> String {
        provider.localizedString(forKey: "Generated by Costivo", comment: "Footer message")
    }
    
    func costEstimateWithClient(_ clientName: String) -> String {
        let format = provider.localizedString(forKey: "Cost Estimate - %@", comment: "Share title with client name")
        return String(format: format, clientName)
    }
    
    // MARK: - Settings Strings
    
    func settings() -> String {
        provider.localizedString(forKey: "Settings", comment: "Settings title")
    }
    
    func support() -> String {
        provider.localizedString(forKey: "Support", comment: "Support section")
    }
    
    func sendFeedback() -> String {
        provider.localizedString(forKey: "Send Feedback", comment: "Send feedback button")
    }
}

// MARK: - Convenience Extension

extension LocalizationService {
    /// Shorthand accessor for shared instance
    static var L: LocalizationService {
        return shared
    }
}
