import Foundation

// MARK: - Localization Key Enum

/// Centralized enum for all localization keys
/// Provides type-safety and prevents typos
enum LocalizationKey: String, CaseIterable {
    // MARK: - Common
    case client = "Client"
    case date = "Date"
    case share = "Share"
    case done = "Done"
    case total = "Total"
    case settings = "Settings"
    
    // MARK: - Share/Export
    case costEstimate = "COST ESTIMATE"
    case materials = "MATERIALS"
    case materialsTotal = "Materials Total:"
    case labor = "LABOR"
    case laborTotal = "Labor Total:"
    case totalCost = "TOTAL COST"
    case totalLabel = "TOTAL:"
    case generatedByCostivo = "Generated by Costivo"
    case costEstimateWithClient = "Cost Estimate - %@"
    
    // MARK: - Settings
    case support = "Support"
    case sendFeedback = "Send Feedback"
    
    // MARK: - Materials
    case noMaterials = "No materials yet"
    case addMaterialToStart = "Add Material"
    
    // MARK: - Jobs
    case jobs = "Jobs"
    case noJobs = "No Jobs"
    case createFirstJob = "Create your first job estimate"
    case searchByClientName = "Search by client name"
}

// MARK: - Localization Protocol

/// Protocol for localization providers
/// Allows easy integration with Phrase, Lokalise, etc.
protocol LocalizationProvider {
    func localizedString(_ key: LocalizationKey) -> String
    func localizedString(_ key: LocalizationKey, _ args: CVarArg...) -> String
}

// MARK: - Default Provider

/// Default localization provider using iOS String Catalogs
struct DefaultLocalizationProvider: LocalizationProvider {
    func localizedString(_ key: LocalizationKey) -> String {
        return NSLocalizedString(key.rawValue, comment: "")
    }
    
    func localizedString(_ key: LocalizationKey, _ args: CVarArg...) -> String {
        let format = NSLocalizedString(key.rawValue, comment: "")
        return String(format: format, arguments: args)
    }
}

// MARK: - Localization Service

/// Centralized localization service
/// Usage: L(.client) or L(.costEstimateWithClient, "John Doe")
class LocalizationService {
    static let shared = LocalizationService()
    
    private var provider: LocalizationProvider
    
    private init(provider: LocalizationProvider = DefaultLocalizationProvider()) {
        self.provider = provider
    }
    
    /// Update the localization provider (e.g., to use Phrase)
    func setProvider(_ provider: LocalizationProvider) {
        self.provider = provider
    }
    
    /// Get localized string for a key
    func callAsFunction(_ key: LocalizationKey) -> String {
        return provider.localizedString(key)
    }
    
    /// Get localized string with format arguments
    func callAsFunction(_ key: LocalizationKey, _ args: CVarArg...) -> String {
        return provider.localizedString(key, args)
    }
}

// MARK: - Convenience

/// Global shorthand for localization
/// Usage: L(.client) or L(.costEstimateWithClient, clientName)
func L(_ key: LocalizationKey) -> String {
    return LocalizationService.shared(key)
}

func L(_ key: LocalizationKey, _ args: CVarArg...) -> String {
    return LocalizationService.shared(key, args)
}
